# -standalone --- что-бы етот конфиг применялся когда приложение розварачивается самостоятельно без спрингКлауд без докера без кубернетиса
eta:
  services:
    catalogue:
      uri: http://localhost:8081

